### PR TITLE
Forget(!)

### PR DESCRIPTION
**Pull request by IndianBoy42**
Add the Forget(!) command that deletes the session file and (if !) does not memorize the session after leaving vim

Also running Memorize! will reenable auto memorize on leave

### CODE REVIEW

**Comment by EricDriussi** [comment]
Well apparently I disabled all GH notifications a while ago -.-U I'm really sorry I'm replying this late: I just saw your PR this morning.

Taking it back to the code itself:
I'm struggling a bit to understand your use case. What exactly do you need for your workflow and why does this PR solve it?
I would also greatly appreciate if you could add some tests and document the behavior in the readme.

Thanks for your time and again, I'm sorry I took so long!

**Comment by IndianBoy42** [comment]
I just want to delete the autosaved session file for the current cwd, usually because something has gone wrong/corrupted or just I know that this session is not something I care about being saved. If i just delete the session file while its open then itll autosave again anyway when closing neovim, so the `:Forget!` variant also removes the saving autocmd. `:Forget!` is usually followed by `:qa`, so it closes and the next time i open `nvim` in this cwd its a completely blank instance. 

The way I usually ended up doing `rm ~/.cache/remember-me/<tab>` and then trying to find the file that corresponds to this directory

**Comment by EricDriussi** [comment]
That sounds pretty reasonable, I'm on board with the idea.
That being said, it would be nice to include tests for the new functionality and some documentation in the `README`.
There's also the (possible) issue I pointed at on the review.

I'm a bit busy ATM and will be for a while, so it might take a bit for me to take care of those things.
If you want to add those changes to the PR however I'll be happy to merge them in!

**Comment by IndianBoy42** [comment]
I'll try and add those things (i'll have to learn how testing works first)

**Comment by EricDriussi** [comment]
Eeeeey!
I had to make some changes to resolve the conflicts and I can't seem to push them to your PR.

I'll open a new one #3 before merging the changes to main, take a look to see if that's your intended outcome!

I also tried to minimize the amount of new code/functionality to ensure ease of use for new users.
If you find anything missing just leave a comment over there and I'll get to it (eventually -.-U), thanks for the contribution!

**Pull request closed without merging**
